### ISSUE TITLE
Combine with https://docs.geoconnex.us into central docs website

### ISSUE THREAD

**Issue by C-Loftus** [internetofwater/geoconnex-guidance#4]
For the purposes of discoverability, I am thinking it might make sense to combine https://docs.geoconnex.us/ with https://internetofwater.github.io/geoconnex-guidance/ When they are separate, we can't link between pages and useful info might be overlooked. 

During the process of combining it might make sense to think about what static site generator is preferred. Since the vast majority of the content is valid markdown we could also pick a different tool if preferred and have a relatively easy switch if we are migrating content anyways.

**Comment by webb-ben** [comment]
+1 for moving this content to https://github.com/internetofwater/docs.geoconnex.us, @ksonda @adplincinst

**Comment by ksonda** [comment]
Yes they need to be consolidated. My personal preference is quarto(guidance), but the particular markdown flavor is a bit different from Jupyter books (docs)

**Comment by C-Loftus** [comment]
I would be happy to work on this if you want! Just so I'm on the same page, do we need certain features from quarto? I feel that unless we need quarto features, while we are refactoring things anyways, it might make sense to switch to a static site generator like [Docusaurus](https://github.com/facebook/docusaurus) specifically meant for documentation websites.

That way the markdown flavor is more general and easier to reuse when necessary, we can also use a wider side of plugins via npm (i.e. we can write all content in markdown but if for some reason in the future we need to bring in a react component for some sort of custom feature, Docusaurus also supports that), and there is an easy way to add translations / versioned docs that might be useful long term as geoconnex grows

I have done [prior work migrating wikis]( https://github.com/TalonCommunity/Wiki/pull/236) so this is up my alley either way. 

If you want to see some docusaurus examples, the following sites are all using it
* https://next-auth.js.org/
* https://reactnative.dev/
* https://www.rabbitmq.com/
* https://talon.wiki/

**Comment by ksonda** [comment]
Quarto has some nice code annotation features but ease in editing and CI is more important. Willing to defer.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by C-Loftus** [comment]
Ok, I can start on a draft PR and we can iterate from there depending on what you like. Certainly flexible with whatever is best for the team. (All please feel free to add opinions!)

Are you referring to the annotation feature in Quarto provided by [hypothes.is](https://web.hypothes.is/)? Just so I understand, what is the use case/persona?  Is it for users reading our docs who want to provide feedback on them for us by annotating notable sections?

There is likely a way to replicate that once I am aligned on use case.

![image](https://github.com/internetofwater/geoconnex-guidance/assets/70598503/fb4eb445-f9e7-4bb3-95c6-6a58302b3d74)

**Comment by ksonda** [comment]
No I’m referring the ability to add numbered in-line hover-over annotations within code blocks. The use case is similar to any footnote

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ksonda** [comment]
As part of this, I think docs.geoconnex.us should have a landing page with 3 or 4 big persona-based links to other parts of the documentation

1.) "how geoconnex works" with the most detailed technical background 
2.) "how to contribute", which could split off into "author guidance" which directs to what is now the guidance docs, and "QuickStart" with some pygeoapi publishing howTos
3.) "use geoconnex" which would have links to the current UIs, maybe R and Python examples for interacting with the reference feature APIs, a placeholder for sparql query examples
4.) a "best practices registry" which is a deliverable for the USGS agreement. Which is an enumeration of things like canonical data models, W3C practices, APIs aligned with use cases, controlled vocabularies, etc. Maybe this is actually part of a content hierarchy under item 2.

**Comment by C-Loftus** [comment]
Done via https://github.com/internetofwater/docs.geoconnex.us/pull/19
